### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by weijia-cheng** [AlejMnoz/james-stephens_the-crock-of-gold#1]
- [x] `se typogrify` comes with changes:

```
wcheng@pop-os:~/git/james-stephens_the-crock-of-gold$ se typogrify .
wcheng@pop-os:~/git/james-stephens_the-crock-of-gold$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/epub/content.opf

no changes added to commit (use "git add" and/or "git commit -a")
```

It looks like there is a character in the long description that `typogrify` doesn't like. I think the typogrify standards are a little different for the metadata so I would accept the change.

- [x] I noticed that your commit ["Add titles"](https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/7d2d5bd4cacb18bc93008ab6dcb4b7ae482a742c) includes some spelling modernization changes. Those would be editorial changes and we should not mix editorial with non-editorial changes in the same commit. In order to fix this you need to perform a [git interactive rebase](https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d) in order to move the changes out of the "Add titles" commit and into the editorial.

I am not sure how familiar you are with git, so I can provide you a short guide for the commands you have to run in case you need them. Sometimes rebases can be hairy but in this case your rebase looks very straightforward (I cloned your repository and tried it myself. Here are some steps:

1. Make a backup of your repository somewhere in case everything goes wrong. I've also forked your repository to be extra safe.
2. Run `git rebase -i 8c5da0bb9f5b2a7e866c8eac43ead373e6080571`. This starts a rebase from the point of the modernize hyphenation and spelling commit. Change the first `pick` in `pick ef2b560 [Editorial] Modernize hyphenation and spelling` to `edit`. Then, when you save and exit this buffer, you will be allowed to stop at this particular commit and update it.
3. Apply the "wellbeing -> well-being" and "stir-about -> stirabout" editorial changes.
4. Run `git add -A` and `git commit --amend` to include the editorial changes into the original editorial PR.
5. Run `git rebase --continue` which concludes the rebase by applying the rest of your changes on top of this. You should notice that after this the spelling changes no longer appear in the "Add titles" commit. (This is a lucky case where rebasing doesn't cause any merge conflicts.)
6. When you have confirmed that the rebase worked, run `git push --force` to push the rewritten history to GitHub.

- [x] Correct me if I'm wrong, but commit [4d257ce93118f20b58b093d61f8ebb00f6a6f3e0](https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/4d257ce93118f20b58b093d61f8ebb00f6a6f3e0) is just a number of typography fixes, and doesn't change any spelling. Since `typogrify` itself is not considered an editorial commit, we would not consider this an editorial commit either. You can rename commits in your git history by doing an interactive rebase like what I suggested above, but instead of using the `pick` command you can can use the `reword` command which only changes the name (and not the actual content) of the commit. Similarly [this commit](https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/f9c73ed31efe63fddec30bfa818a5c93db287167) is also not an editorial commit, because it is just making the text consistent with the scans. A commit is only editorial when it is making a conscious deviation from the text of the scans that might be interpreted as potentially changing the meaning. It looks like you caught on to this distinction in the later commits, which is great.
- [x] You should revert [this commit](https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/451ad2fb381222fb92dd92b104994e9ad01155fb). Periods before ellipses are totally valid and common in our corpus.
- [x] In the colophon, you spelled Böcklin's name as `Böclin`.
- [x] In the long description, it it would make more sense to end the second paragraph with "and virtue and vice" since it is the concluding element of the list.

**Comment by AlejMnoz** [comment]
> It looks like there is a character in the long description that `typogrify` doesn't like. I think the typogrify standards are a little different for the metadata so I would accept the change.

Yes, it was the word joiner before the em dash. Fixed.

> I noticed that your commit ["Add titles"](https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/7d2d5bd4cacb18bc93008ab6dcb4b7ae482a742c) includes some spelling modernization changes. Those would be editorial changes and we should not mix editorial with non-editorial changes in the same commit. In order to fix this you need to perform a [git interactive rebase](https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d) in order to move the changes out of the "Add titles" commit and into the editorial.

Done. Thanks for the guide! I think everything went well.

> Correct me if I'm wrong, but commit [4d257ce93118f20b58b093d61f8ebb00f6a6f3e0](https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/4d257ce93118f20b58b093d61f8ebb00f6a6f3e0) is just a number of typography fixes, and doesn't change any spelling.

Yes, you are right. I was quite confused with those changes because the PG's transcription was very different to the scans I was using, so I was thinking it was based on other scans. Then I realized the reason for all those differences was that PG butchered their own transcription when they removed the hyphenation. After that, I understood that the important part was the scans and not the transcription.

Anyway, I corrected the commit messages.

> * You should revert [this commit](https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/451ad2fb381222fb92dd92b104994e9ad01155fb). Periods before ellipses are totally valid and common in our corpus.

Fixed. My bad.

> * In the colophon, you spelled Böcklin's name as `Böclin`.

Oops.

> * In the long description, it it would make more sense to end the second paragraph with "and virtue and vice" since it is the concluding element of the list.

OK.

I hope that was all... Let me know if I messed everything up.

**Comment by weijia-cheng** [comment]
The rebased history looks very good!

One issue I did see is that [your revert did not apply cleanly](https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/c4146fc44317a0d25e79c40cdef7037c8f02278e). It seems that the attempt to use the revert command created a merge conflict. Can you resolve the merge conflict? Essentially, we'd want to keep all of the changes you've made since removing the periods, while readding the periods. (One way you might consider doing this is `git reset --hard ce9f127bd1e4b87361ae5335ac1b8ec5b318351d` to go back to the "Typogrify content.opf" commit, and then manually readd the periods, redo the last two commits, and then force-push to send the rewritten history to the remote repository. I'd personally prefer doing it this way over having to fix the merge conflict, but you can do either.)

**Comment by AlejMnoz** [comment]
> One way you might consider doing this is `git reset --hard ce9f127bd1e4b87361ae5335ac1b8ec5b318351d` to go back to the "Typogrify content.opf" commit, and then manually readd the periods, redo the last two commits, and then force-push to send the rewritten history to the remote repository.

OK, I followed these instructions (or at least I tried). I believe everything should be all right now. I hope I didn't miss any periods...

**Comment by weijia-cheng** [comment]
Alejandro, it looks like you inadvertently inserted a backslash before the period: https://github.com/AlejMnoz/james-stephens_the-crock-of-gold/commit/d2fcb5245242b4b7e9f7db102b95cffe00f7f1c7#diff-45e82f28543180957edd019bf39a160b177f01c126a661a573233e6c081543daR73
